# TASK level variable

- name: variables form PLAY level
  hosts: localhost
  vars:
    course: "DevOps"
    Triner: "sivakumar"
    duriation: "110HR"
  tasks:
  - name: check variables
    vars: #task level
      course: "devops with cloud"
    ansible.builtin.debug:
      msg: "Hi, I am laurning {{course}}, Trinar is {{Triner}}, duriation is {{duriation}}"