
- name: variables form PLAY level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am laurning {{course}}, Trinar is {{Triner}}, duriation is {{duriation}}"  
  