- name: variables form PLAY level
  hosts: localhost
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am laurning {{course}}, Trinar is {{trainer}}, duriation is {{duriation}}"  